export type ControlRule = {
  id: number;
  priority: "high" | "medium" | "low";
  exception: string;
  controlType: "callback" | "match" | "hold" | "three-way-match" | "dedup-check" | "review";
  controlAction: string;
  owner: string;
  evidenceRequired: string;
  auditTrail: string;
  industries: string[];
  sla: string;
};

export const controlRules: ControlRule[] = [
  {
    id: 1,
    priority: "high",
    exception: "Supplier bank detail changed",
    controlType: "callback",
    controlAction: "Callback verification before payment release",
    owner: "Finance Manager",
    evidenceRequired: "Callback log + old/new bank details",
    auditTrail: "Timestamped approval + decision note",
    industries: ["Freight & logistics", "Wholesale & distribution", "Manufacturing"],
    sla: "24 hrs",
  },
  {
    id: 2,
    priority: "high",
    exception: "Duplicate invoice detected",
    controlType: "match",
    controlAction: "Invoice number + vendor + amount match",
    owner: "AP Clerk",
    evidenceRequired: "Duplicate match record",
    auditTrail: "Exception status + resolution note",
    industries: ["Freight & logistics", "Wholesale & distribution", "Manufacturing"],
    sla: "24 hrs",
  },
  {
    id: 3,
    priority: "high",
    exception: "Amount differs from PO",
    controlType: "three-way-match",
    controlAction: "2-way / 3-way match verification",
    owner: "Department owner",
    evidenceRequired: "PO + invoice comparison",
    auditTrail: "Approval note + variance tolerance",
    industries: ["Wholesale & distribution", "Manufacturing"],
    sla: "48 hrs",
  },
  {
    id: 4,
    priority: "high",
    exception: "Carrier surcharge variance",
    controlType: "match",
    controlAction: "Match against rate card tolerance windows",
    owner: "AP Owner",
    evidenceRequired: "Rate card + actual charge comparison",
    auditTrail: "Approval note + variance percentage",
    industries: ["Freight & logistics"],
    sla: "48 hrs",
  },
  {
    id: 5,
    priority: "high",
    exception: "Missing proof-of-delivery",
    controlType: "hold",
    controlAction: "Hold invoice until POD attached",
    owner: "Ops Finance",
    evidenceRequired: "POD attachment + timestamp",
    auditTrail: "Hold reason + release approval",
    industries: ["Freight & logistics"],
    sla: "72 hrs",
  },
  {
    id: 6,
    priority: "high",
    exception: "PO / invoice mismatch",
    controlType: "three-way-match",
    controlAction: "Three-way match: PO + GRN + invoice",
    owner: "Finance Manager",
    evidenceRequired: "PO + GRN + invoice comparison",
    auditTrail: "Approval note + reconciliation",
    industries: ["Wholesale & distribution", "Manufacturing"],
    sla: "48 hrs",
  },
  {
    id: 7,
    priority: "high",
    exception: "Duplicate invoice variant",
    controlType: "dedup-check",
    controlAction: "Deduplication with tolerance windows",
    owner: "AP Lead",
    evidenceRequired: "Prior payment record + reference analysis",
    auditTrail: "Dedup decision + variance notes",
    industries: ["Freight & logistics", "Wholesale & distribution"],
    sla: "24 hrs",
  },
  {
    id: 8,
    priority: "medium",
    exception: "Supplier statement gap",
    controlType: "callback",
    controlAction: "Callback verification with supplier",
    owner: "Finance Ops",
    evidenceRequired: "Supplier response + reconciliation",
    auditTrail: "Callback log + resolution",
    industries: ["Wholesale & distribution", "Manufacturing"],
    sla: "72 hrs",
  },
  {
    id: 9,
    priority: "medium",
    exception: "Missing invoice receipt",
    controlType: "hold",
    controlAction: "Hold invoice until GRN / receipt confirmed",
    owner: "Receiving Ops",
    evidenceRequired: "GRN / receipt documentation",
    auditTrail: "Hold release + receipt timestamp",
    industries: ["Wholesale & distribution", "Manufacturing"],
    sla: "48 hrs",
  },
  {
    id: 10,
    priority: "medium",
    exception: "Tax code variance",
    controlType: "review",
    controlAction: "Manual tax code review and correction",
    owner: "Finance Controller",
    evidenceRequired: "Tax calculation breakdown + regulation reference",
    auditTrail: "Review approval + tax authority reference",
    industries: ["Wholesale & distribution", "Manufacturing", "Mining & construction"],
    sla: "24 hrs",
  },
  {
    id: 11,
    priority: "medium",
    exception: "Freight charge dispute",
    controlType: "callback",
    controlAction: "Dispute review with carrier / freight partner",
    owner: "Ops Manager",
    evidenceRequired: "Dispute summary + carrier response",
    auditTrail: "Dispute resolution + approval",
    industries: ["Freight & logistics"],
    sla: "72 hrs",
  },
  {
    id: 12,
    priority: "medium",
    exception: "Partial shipment received",
    controlType: "hold",
    controlAction: "Hold invoice for remaining shipment confirmation",
    owner: "Warehouse Manager",
    evidenceRequired: "GRN + remaining shipment confirmation",
    auditTrail: "Hold release + shipment verification",
    industries: ["Wholesale & distribution", "Manufacturing"],
    sla: "48 hrs",
  },
  {
    id: 13,
    priority: "medium",
    exception: "Credit note not matched",
    controlType: "dedup-check",
    controlAction: "Match credit note to original invoice",
    owner: "AP Clerk",
    evidenceRequired: "Original invoice + credit note match record",
    auditTrail: "Match status + offset confirmation",
    industries: ["Wholesale & distribution", "Manufacturing"],
    sla: "48 hrs",
  },
  {
    id: 14,
    priority: "medium",
    exception: "Unusual vendor activity",
    controlType: "callback",
    controlAction: "Callback verification for unrecognized vendor",
    owner: "Finance Manager",
    evidenceRequired: "Vendor verification + purchase authorization",
    auditTrail: "Verification confirmation + approval",
    industries: ["Freight & logistics", "Wholesale & distribution", "Manufacturing"],
    sla: "24 hrs",
  },
  {
    id: 15,
    priority: "low",
    exception: "Reference mismatch",
    controlType: "match",
    controlAction: "Partial reference matching with tolerance",
    owner: "AP Clerk",
    evidenceRequired: "Reference normalization record",
    auditTrail: "Match confidence + manual override (if any)",
    industries: ["Freight & logistics", "Wholesale & distribution"],
    sla: "24 hrs",
  },
  {
    id: 16,
    priority: "low",
    exception: "Split shipment invoice",
    controlType: "three-way-match",
    controlAction: "Aggregate split invoices before 3-way match",
    owner: "Finance Ops",
    evidenceRequired: "All related invoices + consolidated GRN",
    auditTrail: "Aggregation record + approval",
    industries: ["Wholesale & distribution", "Manufacturing"],
    sla: "48 hrs",
  },
  {
    id: 17,
    priority: "low",
    exception: "Tolerance window violation",
    controlType: "review",
    controlAction: "Manual review when variance exceeds threshold",
    owner: "Finance Controller",
    evidenceRequired: "Variance analysis + business justification",
    auditTrail: "Variance approval + tolerance override (if applicable)",
    industries: ["Wholesale & distribution", "Manufacturing", "Mining & construction"],
    sla: "24 hrs",
  },
  {
    id: 18,
    priority: "low",
    exception: "Missing supporting documentation",
    controlType: "hold",
    controlAction: "Hold invoice until supporting docs provided",
    owner: "AP Clerk",
    evidenceRequired: "Invoice + receipt + supporting docs",
    auditTrail: "Hold release + document acknowledgment",
    industries: ["Wholesale & distribution", "Manufacturing", "Mining & construction"],
    sla: "72 hrs",
  },
];

export const controlRuleIndustries = Array.from(
  new Set(controlRules.flatMap((rule) => rule.industries))
).sort();

export const controlTypes = [
  { value: "callback", label: "Callback" },
  { value: "match", label: "Match" },
  { value: "hold", label: "Hold" },
  { value: "three-way-match", label: "Three-way match" },
  { value: "dedup-check", label: "Dedup check" },
  { value: "review", label: "Review" },
];

export const priorities = [
  { value: "high", label: "High" },
  { value: "medium", label: "Medium" },
  { value: "low", label: "Low" },
];
