name: Deploy to Hostinger

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run linter
              run: npm run lint

            - name: Build static site
              run: npm run build:static

            - name: Deploy to Hostinger
              if: github.ref == 'refs/heads/main'
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
                  cname: ${{ secrets.HOSTINGER_DOMAIN }}

            - name: Upload build artifacts
              if: github.ref == 'refs/heads/main'
              uses: actions/upload-artifact@v4
              with:
                  name: static-build
                  path: dist/
                  retention-days: 30
